'use strict';

var EnvironmentActionType = {
  INITIALIZED: 'ENVIROMENT_INITIALIZED',

  // TODO: Separate into environment player action??
  ENVIRONMENT_PLAYER_CONNECTED: 'ENVIRONMENT_PLAYER_CONNECTED',
  ENVIRONMENT_PLAYER_DISCONNECTED: 'ENVIRONMENT_PLAYER_DISCONNECTED',
  ENVIRONMENT_PLAYER_UPDATED: 'ENVIRONMENT_PLAYER_UPDATED'
};

module.exports = EnvironmentActionType;
