'use strict';

var EnvironmentActionType = {
  INITIALIZED: 'ENVIRONMENT_INITIALIZED',

  ENVIRONMENT_PLAYER_CONNECTED: 'ENVIRONMENT_PLAYER_CONNECTED',
  ENVIRONMENT_PLAYER_DISCONNECTED: 'ENVIRONMENT_PLAYER_DISCONNECTED'
};

module.exports = EnvironmentActionType;
